# Generated by Django 6.0 on 2025-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='room_types/')),
                ('total_rooms', models.IntegerField(default=5)),
            ],
        ),
    ]
