# Generated by Django 5.1.1 on 2025-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard Room (2 Person)'), ('family', 'Family Room (4 Person)')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
