# Generated by Django 5.1.1 on 2025-12-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='room_types', to='hotel.facility'),
        ),
    ]
