# Generated by Django 5.1.1 on 2025-12-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_facility_roomtype_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='location',
            field=models.CharField(default='Lantai 1', max_length=100, verbose_name='Letak Kamar'),
        ),
    ]
