# Generated by Django 5.1.1 on 2026-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_roomtype_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
