# Generated by Django 5.1.1 on 2025-12-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw', '0002_alter_vwdestinasi_id_alter_vwpackage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vwpackage',
            name='car_info',
            field=models.TextField(default='-', help_text='Info mobil tersedia. Contoh: Merah (2), Kuning (1)'),
        ),
        migrations.AddField(
            model_name='vwpackage',
            name='destinations',
            field=models.ManyToManyField(related_name='packages', to='vw.vwdestinasi'),
        ),
        migrations.AddField(
            model_name='vwpackage',
            name='duration',
            field=models.CharField(default='-', help_text='Contoh: 2 Jam, 4 Jam', max_length=50),
        ),
        migrations.AddField(
            model_name='vwpackage',
            name='image',
            field=models.ImageField(blank='True', help_text='Foto utama paket', null=True, upload_to='vw_packages/'),
        ),
        migrations.AddField(
            model_name='vwpackage',
            name='slug',
            field=models.SlugField(default='-', help_text='Slug untuk URL (misal: short-trip)', unique=True),
        ),
        migrations.AlterField(
            model_name='vwpackage',
            name='description',
            field=models.TextField(help_text='Deskripsi lengkap paket'),
        ),
        migrations.AlterField(
            model_name='vwpackage',
            name='name',
            field=models.CharField(choices=[('Short Trip', 'Short Trip'), ('Medium Trip', 'Medium Trip'), ('Long Trip', 'Long Trip'), ('Sunrise Trip', 'Sunrise Trip')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vwpackage',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
