# Generated by Django 5.1.1 on 2025-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw', '0003_vwpackage_car_info_vwpackage_destinations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vwpackage',
            name='car_info',
        ),
        migrations.AlterField(
            model_name='vwpackage',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto utama paket', null=True, upload_to='vw_packages/'),
        ),
        migrations.AlterField(
            model_name='vwpackage',
            name='slug',
            field=models.SlugField(help_text='Slug untuk URL (misal: short-trip)', unique=True),
        ),
    ]
