# Generated by Django 5.1.1 on 2026-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw', '0004_remove_vwpackage_car_info_alter_vwpackage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwdestinasi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vwpackage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
