# Generated by Django 5.1.1 on 2026-01-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw', '0005_alter_vwdestinasi_id_alter_vwpackage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VWEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vw_education/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='vw.vwpackage')),
            ],
        ),
    ]
