# Generated by Django 5.1.1 on 2026-01-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw', '0006_vwedukasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vwedukasi',
            name='package',
        ),
        migrations.AddField(
            model_name='vwpackage',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='packages', to='vw.vwedukasi'),
        ),
    ]
