# Generated by Django 5.1.1 on 2025-12-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_alter_menu_id_alter_menucategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='package_content',
            field=models.TextField(blank=True, help_text='Isi paket, pisahkan dengan koma (Contoh: Nasi, Ayam Goreng, Lalapan, Tahu)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.menucategory'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi untuk Menu Harian'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resto_menus/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_package',
            field=models.BooleanField(default=False, verbose_name='Apakah ini Menu Paket?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='min_order_qty',
            field=models.IntegerField(default=1, help_text='Minimal order (Default 15 untuk paket)'),
        ),
    ]
