# Generated by Django 5.1.1 on 2025-12-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_menu_package_content_alter_menu_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
