# Generated by Django 5.1.1 on 2025-12-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_remove_menu_category_delete_menucategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resto_drinks/')),
                ('description', models.TextField(blank=True, help_text='Deskripsi minuman (Opsional)')),
                ('category', models.CharField(choices=[('cold', 'Dingin'), ('hot', 'Panas')], default='cold', max_length=10)),
                ('has_sugar_option', models.BooleanField(default=False, help_text='Centang jika pembeli bisa memilih No Sugar/Less Sugar', verbose_name='Ada Opsi Gula?')),
            ],
        ),
    ]
