# Generated by Django 5.1.1 on 2025-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.AddField(
            model_name='drink',
            name='serving_type',
            field=models.CharField(choices=[('both', 'Bisa Panas & Dingin'), ('ice_only', 'Hanya Dingin'), ('hot_only', 'Hanya Panas')], default='both', max_length=10, verbose_name='Tipe Penyajian'),
        ),
    ]
