# Generated by Django 5.1.1 on 2025-12-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_remove_drink_category_drink_serving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='has_flavor_option',
            field=models.BooleanField(default=False, help_text='Centang jika user bisa memilih: Pedas, Sedang, Gurih', verbose_name='Ada Opsi Rasa?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='min_order_qty',
            field=models.IntegerField(default=1, help_text='Minimal order'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='package_content',
            field=models.TextField(blank=True, help_text='Isi paket, pisahkan dengan koma'),
        ),
    ]
