# Generated by Django 6.0 on 2025-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CART', 'In Cart'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='CART', max_length=20)),
                ('total_amount_gateway', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_vw_booking', models.BooleanField(default=False)),
                ('vw_payment_status', models.CharField(default='NONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemResto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemVW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('total_unit', models.IntegerField()),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
