# Generated by Django 6.0 on 2025-12-24 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('resto', '0001_initial'),
        ('transactions', '0001_initial'),
        ('vw', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemhotel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_items', to='transactions.order'),
        ),
        migrations.AddField(
            model_name='orderitemhotel',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
        migrations.AddField(
            model_name='orderitemresto',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.menu'),
        ),
        migrations.AddField(
            model_name='orderitemresto',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_items', to='transactions.order'),
        ),
        migrations.AddField(
            model_name='orderitemvw',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vw_items', to='transactions.order'),
        ),
        migrations.AddField(
            model_name='orderitemvw',
            name='vw_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vw.vwpackage'),
        ),
    ]
