# Generated by Django 5.1.1 on 2026-01-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0007_menu_has_flavor_option_alter_menu_min_order_qty_and_more'),
        ('transactions', '0003_alter_order_id_alter_orderitemhotel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemresto',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.drink'),
        ),
        migrations.AlterField(
            model_name='orderitemresto',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.menu'),
        ),
    ]
