# Generated by Django 5.1.1 on 2026-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_orderitemresto_drink_alter_orderitemresto_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemhotel',
            name='special_request',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan User'),
        ),
    ]
