# Generated by Django 5.1.1 on 2026-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_order_id_alter_orderitemhotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemhotel',
            name='special_request',
        ),
        migrations.AddField(
            model_name='order',
            name='special_request',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan User'),
        ),
    ]
