# Generated by Django 5.1.1 on 2026-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_orderitemhotel_special_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemresto',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
