# Generated by Django 5.1.1 on 2026-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_orderitemresto_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midtrans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
