# Generated by Django 5.1.1 on 2026-01-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_order_midtrans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bca', 'Bank Transfer / QRIS'), ('hotel', 'Pay at Hotel')], default='bca', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'In Cart'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCEL', 'Cancelled')], default='CART', max_length=20),
        ),
    ]
