# Generated by Django 5.1.1 on 2026-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'In Cart'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('PAY_AT_HOTEL', 'Pay at Hotel'), ('FAILED', 'Failed'), ('CANCEL', 'Cancelled')], default='CART', max_length=20),
        ),
    ]
